import { db } from './db'
import { products } from './schema'

const SEED_PRODUCTS = [
  // ── Cleansers ──────────────────────────────────────────────────────────────
  {
    name: 'Foaming Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    price: '14.99',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Blackheads & pores', 'Oiliness'],
    ingredients: ['niacinamide', 'ceramides', 'hyaluronic acid'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B01N1N5TXO',
  },
  {
    name: 'Hydrating Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    price: '14.99',
    skinTypeMatch: ['dry', 'sensitive'],
    concernsTargeted: ['Dryness', 'Redness'],
    ingredients: ['ceramides', 'hyaluronic acid', 'glycerin'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B00TTD9BRC',
  },
  {
    name: 'Toleriane Hydrating Gentle Cleanser',
    brand: 'La Roche-Posay',
    category: 'cleanser',
    price: '15.99',
    skinTypeMatch: ['sensitive', 'dry'],
    concernsTargeted: ['Redness', 'Dryness'],
    ingredients: ['ceramides', 'niacinamide', 'prebiotic thermal water'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B01MXMNO42',
  },
  {
    name: 'Oil-Free Acne Wash',
    brand: 'Neutrogena',
    category: 'cleanser',
    price: '8.99',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Oiliness'],
    ingredients: ['salicylic acid'],
    isFragranceFree: false,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B00007YCRT',
  },

  // ── Moisturizers ───────────────────────────────────────────────────────────
  {
    name: 'Moisturizing Cream',
    brand: 'CeraVe',
    category: 'moisturizer',
    price: '19.99',
    skinTypeMatch: ['dry', 'sensitive'],
    concernsTargeted: ['Dryness', 'Redness'],
    ingredients: ['ceramides', 'hyaluronic acid', 'petrolatum'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B00TTD9BRC',
  },
  {
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    category: 'moisturizer',
    price: '21.99',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Dryness', 'Dullness'],
    ingredients: ['hyaluronic acid', 'glycerin'],
    isFragranceFree: false,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B00NR1YQK4',
  },
  {
    name: 'Daily Hydrating Lotion',
    brand: 'Cetaphil',
    category: 'moisturizer',
    price: '13.99',
    skinTypeMatch: ['dry', 'sensitive', 'combination'],
    concernsTargeted: ['Dryness'],
    ingredients: ['glycerin', 'niacinamide', 'panthenol'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B005IHT94S',
  },
  {
    name: 'Toleriane Double Repair Face Moisturizer',
    brand: 'La Roche-Posay',
    category: 'moisturizer',
    price: '22.99',
    skinTypeMatch: ['sensitive', 'dry', 'combination'],
    concernsTargeted: ['Dryness', 'Redness'],
    ingredients: ['ceramides', 'niacinamide', 'glycerin', 'prebiotic thermal water'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B01N9SPQHZ',
  },

  // ── Serums ─────────────────────────────────────────────────────────────────
  {
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'serum',
    price: '6.90',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Blackheads & pores', 'Oiliness', 'Uneven skin tone'],
    ingredients: ['niacinamide', 'zinc pca'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B06VWT73GR',
  },
  {
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'serum',
    price: '8.90',
    skinTypeMatch: ['dry', 'sensitive', 'combination', 'oily'],
    concernsTargeted: ['Dryness', 'Dullness', 'Fine lines'],
    ingredients: ['hyaluronic acid', 'panthenol', 'glycerin'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B06VVDD3GH',
  },
  {
    name: 'Vitamin C Serum',
    brand: 'TruSkin',
    category: 'serum',
    price: '19.99',
    skinTypeMatch: ['dry', 'combination', 'oily', 'sensitive'],
    concernsTargeted: ['Dark spots', 'Dullness', 'Uneven skin tone', 'Fine lines'],
    ingredients: ['vitamin c', 'hyaluronic acid', 'vitamin e'],
    isFragranceFree: false,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B01M0XOILF',
  },
  {
    name: 'Discoloration Correcting Serum',
    brand: 'Good Molecules',
    category: 'serum',
    price: '12.00',
    skinTypeMatch: ['dry', 'combination', 'oily', 'sensitive'],
    concernsTargeted: ['Dark spots', 'Uneven skin tone', 'Dullness'],
    ingredients: ['tranexamic acid', 'niacinamide', 'kojic acid'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://goodmolecules.com',
  },

  // ── Toners ─────────────────────────────────────────────────────────────────
  {
    name: 'Witch Hazel Toner — Unscented',
    brand: 'Thayers',
    category: 'toner',
    price: '10.99',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Blackheads & pores', 'Oiliness'],
    ingredients: ['witch hazel', 'aloe vera', 'glycerin'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B07RR9XLBM',
  },
  {
    name: 'Skin Perfecting 2% BHA Liquid Exfoliant',
    brand: "Paula's Choice",
    category: 'toner',
    price: '34.00',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Blackheads & pores', 'Dullness', 'Fine lines'],
    ingredients: ['salicylic acid', 'methylpropanediol', 'butylene glycol'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B0046H5DZ8',
  },

  // ── SPF ────────────────────────────────────────────────────────────────────
  {
    name: 'UV Clear Broad-Spectrum SPF 46',
    brand: 'EltaMD',
    category: 'spf',
    price: '39.00',
    skinTypeMatch: ['sensitive', 'oily', 'combination'],
    concernsTargeted: ['Redness', 'Acne & breakouts'],
    ingredients: ['zinc oxide', 'niacinamide', 'hyaluronic acid'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B002MSN3QQ',
  },
  {
    name: 'Ultra Sheer Dry-Touch SPF 55',
    brand: 'Neutrogena',
    category: 'spf',
    price: '12.99',
    skinTypeMatch: ['oily', 'combination', 'dry', 'sensitive'],
    concernsTargeted: ['Fine lines', 'Dullness'],
    ingredients: ['avobenzone', 'homosalate', 'octisalate'],
    isFragranceFree: false,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B003P2YSD6',
  },
  {
    name: 'Anthelios Melt-in Milk SPF 100',
    brand: 'La Roche-Posay',
    category: 'spf',
    price: '39.99',
    skinTypeMatch: ['sensitive', 'dry'],
    concernsTargeted: ['Redness', 'Dryness'],
    ingredients: ['avobenzone', 'homosalate', 'glycerin'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B01NCJQORE',
  },

  // ── Treatments ─────────────────────────────────────────────────────────────
  {
    name: 'Adapalene Gel 0.1%',
    brand: 'Differin',
    category: 'treatment',
    price: '13.99',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts', 'Fine lines', 'Blackheads & pores'],
    ingredients: ['adapalene'],
    isFragranceFree: true,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B07L1PHSY9',
  },
  {
    name: 'Drying Lotion',
    brand: 'Mario Badescu',
    category: 'treatment',
    price: '12.00',
    skinTypeMatch: ['oily', 'combination'],
    concernsTargeted: ['Acne & breakouts'],
    ingredients: ['salicylic acid', 'sulfur', 'zinc oxide', 'calamine'],
    isFragranceFree: false,
    isVegan: false,
    buyLink: 'https://www.amazon.com/dp/B001B2MFKS',
  },
  {
    name: 'Acne Spot Dots',
    brand: 'Peach Slices',
    category: 'treatment',
    price: '4.99',
    skinTypeMatch: ['oily', 'combination', 'sensitive'],
    concernsTargeted: ['Acne & breakouts'],
    ingredients: ['hydrocolloid'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B07DKMQXJF',
  },
  {
    name: 'Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    category: 'treatment',
    price: '9.90',
    skinTypeMatch: ['dry', 'combination', 'oily', 'sensitive'],
    concernsTargeted: ['Dark spots', 'Uneven skin tone'],
    ingredients: ['alpha arbutin', 'hyaluronic acid'],
    isFragranceFree: true,
    isVegan: true,
    buyLink: 'https://www.amazon.com/dp/B07QMFMJG5',
  },
]

async function seed() {
  console.log(`Seeding ${SEED_PRODUCTS.length} products…`)

  await db.delete(products)
  await db.insert(products).values(SEED_PRODUCTS)

  console.log('Done.')
  process.exit(0)
}

seed().catch((err) => {
  console.error(err)
  process.exit(1)
})
